### ISSUE TITLE
CSS Request - Blur and Darken

### ISSUE THREAD

**Issue by Crenshaw1312** [Crenshaw1312/SpotifyBackgrounds#4]
**Discord**
KortyBoi# 0001

**CSS Code**
```css
/*/// ActivityBackgrounds ///*/
:root {
    --blur: 3px;
}
.panels-j1Uci_::after {
    backdrop-filter: blur(var(--blur));
    background-color: rgba(0, 0, 0, 0.25);
}
.headerTop-3C2Zn0 {
    backdrop-filter: blur(var(--blur));
    background-color: rgba(0, 0, 0, 0.25);
}
.activity-11LB_k {
    backdrop-filter: blur(var(--blur));
    background-color: rgba(0, 0, 0, 0.25);
}
.header-QKLPzZ {
    backdrop-filter: blur(var(--blur));
    background-color: rgba(0, 0, 0, 0.25);
}
```

**What does it do?**
This adds a slightly darker background (for lighter covers) and adds blur for a nicer effect. Use blur slider(s) to control

**Images/Attachments**
![image](https://kortyboi.com/img/upload/DiscordCanary_FHQuWalsGf.png)
